close all
clearvars -except Param

frameSynchronizer = FramePreambleDetector( ...
    LSFPreamble = Param.Preamble.LSF,...
    BERTPreamble = Param.Preamble.BERT, ...);
    ENDPreamble = Param.Preamble.BERT, ...
    LSFSyncBurst = Param.SyncBurst.LSF, ...
    BERTSyncBurst = Param.SyncBurst.BERT, ...
    StreamSyncBurst = Param.SyncBurst.Stream, ...
    PacketSyncBurst = Param.SyncBurst.Packet, ...
    ThresholdMetric = 6);