rctFilt = comm.RaisedCosineTransmitFilter( ... 
      'OutputSamplesPerSymbol', 2);
  varDelay = dsp.VariableFractionalDelay; 
  awgnChan = comm.AWGNChannel( ...
      'NoiseMethod',  'Signal to noise ratio (SNR)', ...
      'SNR',          15, ...
      'SignalPower',  0.5, ... 
      'RandomStream', 'mt19937ar with seed');
  rcrFilt = comm.RaisedCosineReceiveFilter( ...
      'InputSamplesPerSymbol',  2, ...
      'DecimationFactor',       1);
  constDiag1 = comm.ConstellationDiagram( ...
      'SamplesPerSymbol', 2, ...
      'XLimits',         [-2 2], ...
      'YLimits',         [-2 2], ...
      'Title',           'Before Symbol Synchronizer', ...
      'Position',        [400 400 400 400]);
  symsync = comm.SymbolSynchronizer( ... 
      'SamplesPerSymbol', 2, ...
      'DampingFactor', sqrt(2)/2, ...
      'NormalizedLoopBandwidth', 0.01);
  constDiag2 = comm.ConstellationDiagram( ...
      'XLimits',  [-2 2], ...
      'YLimits',  [-2 2], ...
      'Title',    'After Symbol Synchronizer', ...
      'Position', [1000 400 400 400]);

  rng(100);
  for i = 1:100
      data      = randi([0 3], 100, 1);           % Random data
      txSym     = pskmod(data,4,pi/4);            % QPSK modulation
      txSample  = rctFilt(txSym);                 % Transmit filter
      chanDelay = varDelay(txSample, 0.05*(i-1)); % Variable delay
      chanOut   = awgnChan(chanDelay);            % AWGN channel
      rxSample  = rcrFilt(chanOut);               % Receive filter
      % Constellation diagram view before symbol synchronizer
      constDiag1(rxSample);             
      rxSym     = symsync(rxSample);              % Symbol synchronizer
      % Constellation diagram view after symbol synchronizer. Skip some
      % frames of irregular length as the Constellation Diagram object
      % does not allow input frame length change.
      if length(rxSym) == 100                 
        constDiag2(rxSym);
      end
  end