% Generated by MATLAB(R) 24.2 (R2024b) and Communications Toolbox 24.2 (R2024b).
% Generated on: 24-Mar-2025 13:40:29

%% Generating PSK waveform
% PSK configuration
M = 4; 	 % Modulation order
% input bit source:
pn = comm.PNSequence('Polynomial', 'x9+x5+1', 'InitialConditions', [zeros(1, 8) 1]);
pn.SamplesPerFrame = 192*2;
in = pn();
usedInput = in(1:log2(M)*(floor(length(in)/log2(M))));
symbolInput = bit2int(usedInput, log2(M));

% Generation
phaseOffset = pi/M;
waveform = pskmod(symbolInput, M, phaseOffset, 'bin');

Fs = 9000; 								 % Specify the sample rate of the waveform in Hz

%% Impairments
%% Visualize
% Time Scope
timeScope = timescope('SampleRate', Fs, ...
    'TimeSpanOverrunAction', 'scroll', ...
    'TimeSpanSource', 'property', ...
    'TimeSpan', 0.0033333);
timeScope(waveform);
release(timeScope);

% Spectrum Analyzer
spectrum = spectrumAnalyzer('SampleRate', Fs);
spectrum(waveform);
release(spectrum);

% Constellation Diagram
constel = comm.ConstellationDiagram('ColorFading', true, ...
    'ShowTrajectory', 0, ...
    'ShowReferenceConstellation', false);
constel(waveform);
release(constel);


