% Build a cascade (row vector) of RF elements
elements(1) = rfelement(OIP3=19);
elements(2) = rfantenna( ...
    'Type','TransmitReceive', ...
    'Gain',[2.1 2.1], ...
    'PathLoss',60);
elements(3) = rfelement( ...
    NF=3, ...
    OIP2=45, ...
    OIP3=-14);

% Construct an rfbudget object
b = rfbudget( ...
    Elements=elements, ...
    InputFrequency=2.4e9, ...
    AvailableInputPower=7.5, ...
    SignalBandwidth=20e6, ...
    Solver='HarmonicBalance', ...
    AutoUpdate=true);
